default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: giftdb_dev

test:
  <<: *default
  database: giftdb_test

production:
  <<: *default
  database: giftdb
