# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57829b16fbd3e1b1cbacb39471839092103c44456e16322da0cb83f1d9707515854dff338ebc27c58e0464f9ef60380d5c48a789100c8ca20b7f22fda72dcb4c

test:
  secret_key_base: 167d2982d23a42b4d4beb4e36ff5e000ee986c85d8525f425b1f977f1a993cf8da6c2f7d8fefb57ebbfb247786fe75c0529d4076546caa831efd21eaa7b4c1bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
